spring:
  config:
    additional-location: file:/Users/wf2311/config/pig/
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
    include: config
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888

